catalanomircosav/QT

- Attribute.java
> Definita la classe astratta Attribute

- ContinuousAttribute.java
> Aggiunta classe concreta ContinuousAttribute

- DiscreteAttribute.java
> Aggiunta della classe DiscreteAttribute

- Data.java
> Aggiunta della classe Data

- Data.java
**PR** relativo a: #4 
**DA MERGIARE DOPO L'ISSUE #3**
> Aggiunto main alla classe Data

- Attribute.java
- DiscreteAttribute.java
- Item.java
**PR** per:
1. aggiunta la classe `item` astratta,
2. risolti problemi minori di parentesi graffe **{**,
3. risolto javadoc non corretto (**parametri non descritti**).
> Aggiunta la classe astratta Item e risolti problemi minori.

- Data.java
> Aggiunto metodo getItemSet

- Tuple.java
> Inserita classe Tuple

- ArraySet.java
> Aggiunta classe ArraySet

- Cluster.java
**PR** per:
1. aggiunta classe `Cluster`
> Aggiunta la classe Cluster

- ArraySet.java
- ClusterSet.java
- Tuple.java
**PR** per:
1. Aggiunta classe `ClusterSet`
2. Risolti problemi di generazione `javadoc`.
> Aggiunta classe ClusterSet e corretti problemi minori.

- QTMiner.java
PR relativa a: #21 
Dai un occhiata, ti inserisco anche il codice commentato da deepseek
```java
private Cluster buildCandidateCluster(Data data, boolean[] isClustered) {
Cluster bestCluster = null; // Miglior cluster trovato
int maxSize = 0;            // Dimensione del miglior cluster
// Scansiona tutte le tuple del dataset
for (int i = 0; i < data.getNumberOfExamples(); i++) {
// Se la tupla i-esima non è clusterizzata
if (!isClustered[i]) {
// Crea un nuovo cluster con la tupla i come centroide
Tuple centroid = data.getItemSet(i);
Cluster currentCluster = new Cluster(centroid);
currentCluster.add(i); // Aggiungi la tupla i al cluster
// Confronta il centroide con tutte le altre tuple
for (int j = 0; j < data.getNumberOfExamples(); j++) {
if (i != j && !isClustered[j]) {
Tuple other = …
```
> Inserita classe di prova

- QTMiner.java
PR relativa a: #21
Ho sistemato alcuni errori, ne rimangono 2 su 
currentCluster.add(j);
dove dice The method add(int) is undefined for the type Cluster
non so come risolvere
> Sistemati alcuni errori, ne rimangono 2

- Keyboard.java
**PR** per #37:
1. Aggiunta classe Keyboard per l'input da tastiera.
> Aggiunta classe Keyboard per l'input da tastiera.

- MainTest.java
- data/Attribute.java
- data/ContinuousAttribute.java
- data/ContinuousItem.java
- data/Data.java
- data/DiscreteAttribute.java
- data/DiscreteItem.java
- data/Item.java
- data/Tuple.java
- keyboardinput/Keyboard.java
- mining/Cluster.java
- mining/ClusterSet.java
- mining/QTMiner.java
- utility/ArraySet.java
> Definiti package e modificate visibilità.

- MainTest.java
> Modificato MainTest per aggiunta interazione con utente.

- data/Data.java
**PR** per:
- Convertito l'array `attributeSet` in una _lista dinamica_.
> Modificata la classe Data secondo le specifiche richieste.

- data/Data.java
- data/Tuple.java
- mining/Cluster.java
**PR** per:
- modificata la firma di `avgDistance`.
related to: #60.
> Modificata la funzione avgDistance

- MainTest.java
- data/DiscreteAttribute.java
> Sistemato DiscreteAttribute e sistemato problema nel main

- data/DiscreteAttribute.java
- mining/Cluster.java
- mining/QTMiner.java
> Modifiche a Cluster e di consguenza QTMiner + minor fix

- mining/ClusterSet.java
**PR** per:
- riorganizzata la classe `Clusterset`.
related to: #61.
> Riorganizzazione del ClusterSet

- data/ContinuousItem.java
> Aggiunta ContinuousItem

- data/ContinuousItem.java
- data/DiscreteItem.java
- data/Item.java
- data/Tuple.java
> Aggiornato tutto con Generics
